config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get  'login/new',             to: 'logins#new', as: :new_login
  get  'login/cookiesrequired', to: 'logins#cookiesrequired', as: :cookiesrequired_login
  post 'login/create',          to: 'logins#create', as: :create_login
  get  'login/create',          to: redirect('/login/new')
  get  'login/destroy',         to: 'logins#destroy', as: :destroy_login

  post 'accounts/verify',       to: 'accounts#verify', as: :verify_account
  get  'accounts/setup/:token', to: 'accounts#setup',  as: :setup_account
  get  'accounts/:id/delete', to: 'accounts#delete',  as: :delete_account
  resources :accounts

  get 'lists/:email', to: 'lists#by_email', constraints: { email: /([\S]+@[\S]+)/ }
  get 'lists/:id/subscriptions', to: 'lists#subscriptions', as: :list_subscriptions
  get 'lists/:id/new_subscription', to: 'lists#new_subscription', as: :new_list_subscription
  get 'lists/:id/delete', to: 'lists#delete',  as: :delete_list
  resources :lists do
    get    'keys',              to: 'keys#index'
    get    'keys/new',          to: 'keys#new', as: :key_new
    get    'keys/:fingerprint', to: 'keys#show', as: :key
    delete 'keys/:fingerprint', to: 'keys#destroy'
    post   'keys',              to: 'keys#create', as: 'key_create'
  end

  resources  :subscriptions do
    member do
      get 'delete'
    end
  end

  root 'accounts#home'
end

app/models/list.rb
class List < Base
  has_many :subscriptions
  add_response_method :http_response

  def to_s
    email
  end

  def keys(fingerprint=nil)
    params = {params: { list_id: self.id}}
    if fingerprint.present?
      Key.find(fingerprint, params)
    else
      Key.all(params)
    end
  end

  def key
    @key ||= Key.find(fingerprint, params: { list_id: self.id })
  rescue ActiveResource::ResourceNotFound
    nil
  end

  def may_delete_keys?(account)
    if account.superadmin? || account.admin_lists.include?(self)
      true
    else
      (Array(Conf.lists_on_which_subscribers_may_delete_keys) & [self.email, '*']).any?
    end
  end

  def headers_to_meta
    @headers_to_meta ||= Array(attributes['headers_to_meta']).join("\n")
  end

  def bounces_drop_on_headers
    Rails.logger.info "bdoh: #{attributes['bounces_drop_on_headers'].inspect}"
    @bounces_drop_on_headers ||= Hash(attributes['bounces_drop_on_headers'].attributes).map do |k,v|
      "#{k}: #{v}"
    end.join("\n")
  end

  def admins
    subscriptions.select do |subscription|
      subscription.admin?
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_load_and_authorize_resource only: :create

  def new
    @list = List.build
  end

  def index
    redirect_to root_path
  end

  def edit
    @keywords = %w[subscribe unsubscribe list-subscriptions set-fingerprint resend resend-encrypted-only sign-this add-key delete-key list-keys get-key fetch-key]
  end

  def show
    redirect_to list_subscriptions_path
  end

  def by_email
    email = params[:email]
    current_user.subscriptions.map(&:list).each do |list|
      if list.email == email
        return redirect_to list_subscriptions_path(id: list.id)
      end
    end
    redirect_to root_path
  end

  def subscriptions
    @admins = @list.admins
    @non_admins = @list.subscriptions - @list.admins
  end

  def new_subscription
    # Necessary for the shared form.
    @subscription = Subscription.build
    # ActiveResource doesn't actually merge attributes given to build() (it's a
    # bug fixed for versions requiring rails5), so we assign the list manually.
    @subscription.list_id = @list.id
  end

  def create
    @old_timeout = List.timeout
    List.timeout = 120
    @list = List.new(new_list_params)
    authorize! :create, @list
    if @list.save
      put_api_messages_as_flash_error
      redirect_to @list, notice: "✓ List created."
    else
      render 'new'
    end
  rescue ActiveResource::TimeoutError => exc
    logger.warn "Timeout while creating list: #{exc.inspect}"
    render 'timeout_on_create'
  ensure
    List.timeout = @old_timeout
  end

  def update
    logger.info list_params.inspect
    if @list.update_attributes(list_params)
      redirect_to edit_list_path(@list), notice: "✓ Options saved."
    else
      render 'edit'
    end
  end

  def destroy
    if list = @list.destroy
      redirect_to current_account, notice: "✓ List #{@list.email} deleted."
    else
      redirect_to list, error: "Deleting list failed!"
    end
  end

  private 

  def new_list_params
    params.require(:list).permit(:email, :fingerprint)
  end

  def list_params
    # TODO: Improve readability of this code.
    p = params.require(:list).permit!
    if p['headers_to_meta'].is_a?(String)
      p['headers_to_meta'] = p['headers_to_meta'].split("\n").map { |h| h.strip }
    end
    # TODO: Why are there sometimes empty values in these two keys?
    p['keywords_admin_only'] = p['keywords_admin_only'].map {|v| v.presence || nil }.compact
    p['keywords_admin_notify'] = p['keywords_admin_notify'].map {|v| v.presence || nil }.compact
    # Convert these into a hash.
    p['bounces_drop_on_headers'] = p['bounces_drop_on_headers'].to_s.strip.split("\n").inject({}) do |memo, line|
      name, value = line.split(':').map(&:strip)
      if name.present? && value.present?
        memo[name] = value
      end
      memo
    end
    p
  end
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/lists/_form.html.haml
.col-sm-12
  %h2.text-default List options

  = simple_form_for(@list, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
    %fieldset
      %legend Subject prefixes
      = f.input :subject_prefix, hint: "If you want brackets, add them here, too."
      = f.input :subject_prefix_in, label: 'Subject-prefix for incoming emails', hint: "If you want brackets, add them here, too."
      = f.input :subject_prefix_out, label: 'Subject-prefix for outgoing emails', hint: "If you want brackets, add them here, too."

    %fieldset
      %legend Footer
      = f.input :public_footer, as: :text
      = f.input :internal_footer, as: :text

    %fieldset
      %legend Message control
      = checkbox f, :keep_msgid, "Pass incoming Message-IDs to outgoing messages? This enables threading in Mail-clients and helps to identify messages."
      = checkbox f, :munge_from, "Include the original sender's email address into the From header of outgoing messages? If this is enabled recipients can see who sent the email before decrypting the content. Some people like that, but be aware that this puts information into the open which otherwise might have been hidden (depending on the encryption of the messages)."
      = checkbox f, :set_reply_to_to_sender, "Set a Reply-To header to outgoing messages, which contains the originally incoming Reply-To value, or the incoming From value? If this is enabled replies will by default be sent to this email address instead of to the list. PLEASE BEWARE: this might result in ACCIDENTALLY REVEALED EMAIL ADDRESSES of subscribers even to non-subscribers!"
      = f.input :max_message_size_kb, hint: "Emails bigger than this will be rejected (measured in kilo-bytes.)"
      = f.input :headers_to_meta, hint: "One header-name per line. Case-insensitive.", as: :text

    %fieldset
      %legend Send control
      = checkbox f, :send_encrypted_only, "Only send messages if they can be encrypted to the subscribed receiver (does not apply to resend messages)."
      = checkbox f, :deliver_selfsent, "Should e-mails be delivered to the original subscribed sender? (Works only with signed emails.)"

    %fieldset
      %legend Receive control
      = checkbox f, :receive_admin_only, "Only accept messages validly signed by an admin of this list? (Determined by fingerprint.)"
      = checkbox f, :receive_authenticated_only, "Only accept messages that are validly signed by a subscriber? (Determined by fingerprint.)"
      = checkbox f, :receive_signed_only, "Only accept validly signed messages?"
      = checkbox f, :receive_encrypted_only, "Only accept encrypted messages?"
      = checkbox f, :receive_from_subscribed_emailaddresses_only, "Only accept messages with a subscribed address as From-header? (Warning: this is a very weak check!)"

    %fieldset
      %legend Keyword control
      = f.input :keywords_admin_only, as: :check_boxes, collection: @keywords, hint: "Selected keywords may only be called by admins of this list.", wrapper: :horizontal_radio_and_checkboxes
      = f.input :keywords_admin_notify, as: :check_boxes, collection: @keywords, hint: "Admins will be notified whenever one of these keywords is called.", wrapper: :horizontal_radio_and_checkboxes


    %fieldset
      %legend Advanced: Message headers
      = checkbox f, :include_list_headers, "Include List-headers (RFC 2369) to outgoing messages."
      = checkbox f, :include_openpgp_header, "Include OpenPGP-headers to outgoing messages."
      = f.input :openpgp_header_preference, collection: %w[signencrypt encrypt sign], hint: "Only relevant if inclusion of OpenPGP-headers is active."
    %fieldset
      %legend Advanced: Bounce handling
      = f.input :bounces_drop_on_headers, placeholder: 'X-Spam-Flag: yes', hint: 'One match per line. Case-insensitive.', as: :text
      = checkbox f, :bounces_drop_all, "Don't bounce but drop all rejected messages."
      = checkbox f, :bounces_notify_admins, "Notify admins of bounced messages."
    %fieldset
      %legend Advanced: Other settings
      = f.input :log_level, collection: %w[error warn info debug]

    %fieldset
      %legend Submit
      = f.button :submit, 'Update', class: 'btn btn-primary'

app/views/lists/_list.html.haml
= link_to list.email, list

app/views/lists/_subscription_row.html.haml
.card
  .card_icon= image_tag 'person.svg', width: '30px'
  .card_text
    = render "subscriptions/subscription", subscription: subscription
  .card_info
    - if subscription.fingerprint.blank?
      = popup('key-missing.svg') do
        .warn Warning: This address has no key selected!
        = link_to("Fix this", edit_subscription_path(subscription))
    - elsif subscription.key.blank?
      = popup('key-missing.svg') do
        .warn Warning: The key that is selected for this address is not available!
        = link_to("Fix this", edit_subscription_path(subscription))
    - elsif subscription.key.trust_issues.present?
      = popup('key-missing.svg') do
        .warn= key_trust_title(subscription.key)
        = link_to("Fix this", edit_subscription_path(subscription))

    - if ! subscription.delivery_enabled?
      = popup('delivery-disabled.svg') do
        This person currently does not receive emails from this list ("delivery disabled").
    - if subscription.admin?
      = popup('heart.svg') do
        This person is an admin of this list.

app/views/lists/delete.html.haml
- @title = "Delete list"

.col-lg-6.col-md-6

  %h2 #{@title} #{@list.email}?

  %p{style: 'margin: 3em 0'}
    %strong 
      Are you really sure?
      This can
      %em not
      be undone!


  .pull-right
    = button_to(@list, method: :get, class: 'btn btn-link') do
      = t(".back_to_list")

  = button_to @list, method: :delete, class: 'btn btn-danger' do
    .glyphicon.glyphicon-remove
    Delete list now! 

app/views/lists/edit.html.haml
- @title = 'List options'

= render 'form'

- if can? :destroy, @list
  .pull-right{style: 'margin-top: 3em'}
    = link_to delete_list_path(@list), class: 'text-danger' do
      .glyphicon.glyphicon-remove
      Delete list 

app/views/lists/new.html.haml
- @title = t(".title")

.col.col-sm-12
  %fieldset
    %legend
      = t(".create_list")
  
    = simple_form_for(@list, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
      = f.input :email, hint: t(".hint_email"), required: true
      = f.input :fingerprint, label: t(".fingerprint"), hint: t(".hint_fingerprint")
      = f.button :submit, t(".create"), class: 'btn btn-success'

app/views/lists/new_subscription.html.haml
- @title = t("lists.subscriptions.new_subscription")

.col-sm-12
  %h2= @title

  = render "subscriptions/form"

app/views/lists/subscriptions.html.haml
- @title = t(".title")

.col.col-sm-12

  .pull-right
    = link_to(new_list_subscription_path(@list), method: :get, class: 'text-success') do
      %span.glyphicon.glyphicon-plus
      = t(".new_subscription")

  %h2= @title

  .card_listing
    - @admins.each do |subscription|
      = render "subscription_row", subscription: subscription

  .card_listing
    - @non_admins.each do |subscription|
      = render "subscription_row", subscription: subscription

app/views/lists/timeout_on_create.html.haml
%h1 Time out.

%p We waited for a long time but the Schleuder API didn't answer. This happens sometimes when creating a new list because generating a new OpenPGP key-pair (for the new list) requires a lot of randomness — if that's not given, GnuPG just waits until there's more.

%p
  Unfortunately we can't see from here what the issue really is. But chances are that the list was created just fine and in a few minutes the new OpenPGP key-pair will have been generated, too. So please wait a little while and then
  = link_to root_path, 'have a look if your list was created.'