config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get  'login/new',             to: 'logins#new', as: :new_login
  get  'login/cookiesrequired', to: 'logins#cookiesrequired', as: :cookiesrequired_login
  post 'login/create',          to: 'logins#create', as: :create_login
  get  'login/create',          to: redirect('/login/new')
  get  'login/destroy',         to: 'logins#destroy', as: :destroy_login

  post 'accounts/verify',       to: 'accounts#verify', as: :verify_account
  get  'accounts/setup/:token', to: 'accounts#setup',  as: :setup_account
  get  'accounts/:id/delete', to: 'accounts#delete',  as: :delete_account
  resources :accounts

  get 'lists/:email', to: 'lists#by_email', constraints: { email: /([\S]+@[\S]+)/ }
  get 'lists/:id/subscriptions', to: 'lists#subscriptions', as: :list_subscriptions
  get 'lists/:id/new_subscription', to: 'lists#new_subscription', as: :new_list_subscription
  get 'lists/:id/delete', to: 'lists#delete',  as: :delete_list
  resources :lists do
    get    'keys',              to: 'keys#index'
    get    'keys/new',          to: 'keys#new', as: :key_new
    get    'keys/:fingerprint', to: 'keys#show', as: :key
    delete 'keys/:fingerprint', to: 'keys#destroy'
    post   'keys',              to: 'keys#create', as: 'key_create'
  end

  resources  :subscriptions do
    member do
      get 'delete'
    end
  end

  root 'accounts#home'
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action :authenticate
  skip_load_and_authorize_resource
  skip_authorization_check

  def cookiesrequired
    if session[:cookietest] == true
      redirect_to new_login_url
    end
  end

  def new
    # No session-cookie means first request or cookies disabled. If it's the
    # first request the cookierequired-test will redirect back here and then
    # we've got a session.
    if cookies[sessionkey].blank?
      session[:cookietest] = true
      redirect_to cookiesrequired_login_url
      return
    end
    if current_account
      redirect_to '/'
    end
  end

  def create
    account = Account.find_by(email: params[:email])
    if account.try(:authenticate, params[:password])
      session[:current_account_id] = account.id
      update_session_expiry
      if session[:return_to].present?
        redirect_to session[:return_to]
        session[:return_to] = nil
      else
        redirect_to account
      end
    else
      flash.now[:error] = 'Wrong email-address or password, please try again.'
      render :new, :status => 401
    end
  end

  def destroy
    log_out "Logout successful. Have a nice day!"
  end

  private

  def sessionkey
    Rails.application.config.session_options[:key]
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/cookiesrequired.html.haml
- @title = 'Cookies required'

Please enable cookies for this domain and 
= link_to 'try again', new_login_url

app/views/logins/new.html.haml
- @title = t(".title")

.col-lg-6
  %p{style: 'margin-bottom: 3em'}= t(".hint")
  = form_tag(create_login_path, { class: 'form-horizontal', role: 'form' }) do
    .form-group
      = label_tag :email, t(".email"), class: 'col-sm-2 control-label'
      .col-sm-6= text_field_tag :email, '', placeholder: t(".hint_email"), class: 'form-control'
    .form-group
      = label_tag :password, t(".password"), class: 'col-sm-2 control-label'
      .col-sm-6= password_field_tag :password, '', placeholder: t(".hint_password"), class: 'form-control'
    = button_tag t(".login"), class: 'btn btn-primary'
    = link_to t(".create_account"), new_account_path