config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get  'login/new',             to: 'logins#new', as: :new_login
  get  'login/cookiesrequired', to: 'logins#cookiesrequired', as: :cookiesrequired_login
  post 'login/create',          to: 'logins#create', as: :create_login
  get  'login/create',          to: redirect('/login/new')
  get  'login/destroy',         to: 'logins#destroy', as: :destroy_login

  post 'accounts/verify',       to: 'accounts#verify', as: :verify_account
  get  'accounts/setup/:token', to: 'accounts#setup',  as: :setup_account
  get  'accounts/:id/delete', to: 'accounts#delete',  as: :delete_account
  resources :accounts

  get 'lists/:email', to: 'lists#by_email', constraints: { email: /([\S]+@[\S]+)/ }
  get 'lists/:id/subscriptions', to: 'lists#subscriptions', as: :list_subscriptions
  get 'lists/:id/new_subscription', to: 'lists#new_subscription', as: :new_list_subscription
  get 'lists/:id/delete', to: 'lists#delete',  as: :delete_list
  resources :lists do
    get    'keys',              to: 'keys#index'
    get    'keys/new',          to: 'keys#new', as: :key_new
    get    'keys/:fingerprint', to: 'keys#show', as: :key
    delete 'keys/:fingerprint', to: 'keys#destroy'
    post   'keys',              to: 'keys#create', as: 'key_create'
  end

  resources  :subscriptions do
    member do
      get 'delete'
    end
  end

  root 'accounts#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate
  before_action :set_locale
  load_and_authorize_resource
  # ensure authorization is checked.
  check_authorization

  helper_method :current_account
  helper_method :current_user

  rescue_from ActiveRecord::RecordNotFound, ActiveResource::ResourceNotFound do |exception|
    render_404
  end

  rescue_from CanCan::AccessDenied do |exception|
    render_error(403, :forbidden)
  end

  rescue_from ActiveResource::ForbiddenAccess do |exception|
    logger.error "API denied access! Check if the fingerprint of your certificate has been added to the list of fingerprints at the schleuder-server."
    render_error(:api_denied, :forbidden)
  end

  # Happens when fingerprint verification failed.
  rescue_from ActiveResource::SSLError do |exception|
    logger.error "SSLError: #{exception.inspect}"
    case exception.message
    when /certificate verify failed/
      @reason = "The API sent different TLS-fingerprint than we expected, check your settings."
    else
      @reason = exception.message
    end
    render_error(:ssl_error, :forbidden)
  end

  rescue_from ActiveResource::BadRequest do |exc|
    logger.error "API response: #{exc.response}"
    logger.error "API response headers: #{exc.response.to_hash.inspect}"
    logger.error "API response body: #{exc.response.body}"
    raise exc
  end

  rescue_from Errno::ECONNREFUSED do |exc|
    logger.error exc.inspect
    logger.error exc.backtrace.join("\n")
    render_error(:missing_schleuder_api, 500)
  end

  rescue_from ActiveResource::TimeoutError do |exc|
    logger.error exc.inspect
    logger.error exc.backtrace.join("\n")
    render_error(:timeout, 500)
  end

  private

  # Keep single method for 404 to make it easier to overwrite it.
  def render_404
    render 'errors/404', :status => :not_found, layout: 'error'
  end

  def render_error(view, status)
    render "errors/#{view}", status: status, layout: 'error'
  end

  def current_account
    @current_account ||= session[:current_account_id] &&
        Account.find(session[:current_account_id])
  end
  # Many expect current_user()
  alias_method :current_user, :current_account

  def current_account=(account)
    @current_account = account
  end

  def update_session_expiry
    if current_account
      session[:login_expires_at] = 30.minutes.from_now
    end
  end

  def valid_login_session?
    if session[:login_expires_at].blank?
      false
    else
      expiry = Time.parse(session[:login_expires_at])
      current_account && expiry > Time.now
    end
  end

  def authenticate
    if valid_login_session?
      update_session_expiry
    else
      session[:return_to] = request.fullpath
      log_out t("please_log_in")
    end
  rescue => e
    logger.error "Error: #{e}"
    log_out "Error.", :error
  end

  def set_locale
    if params['lang'].present?
      lang_param = params['lang'].to_sym
      if I18n.available_locales.include?(lang_param)
        I18n.locale = lang_param
      end
    end
  end

  def log_out(msg, msg_type=:notice)
    current_account = session[:current_account_id] = nil
    redirect_to new_login_url, flash: { msg_type => msg }
  end

  def load_resource
    var_name = controller_name.singularize
    var = controller_name.classify.constantize.find(params[:id])
    instance_variable_set("@#{var_name}", var)
  end

  def put_api_messages_as_flash_error
    if messages = Base.connection.http_response.headers[:x_messages]
      flash[:error] = messages
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def make_breadcrumb
    url_for.split('/').map do |part|
      # Skip IDs, we use the instance variable to go easier on the database.
      next if part.to_i > 0 || part.blank?

      obj = instance_variable_get("@#{part.singularize}")
      # Don't link action's names ("edit").
      next if obj.blank? && !current_page?(action: :index)

      index_url = url_for(controller: part, action: :index)
      index_name = part.humanize.pluralize.titleize
      out = bc_part(index_name, index_url)

      if obj
        if obj.id
          obj_url = url_for(controller: part, action: :show, id: obj.id)
          out << bc_part(obj.email, obj_url)
        else
          out << bc_part(obj.email.presence || 'New', nil)
        end
      end
      out
    end.compact.join.html_safe
  end

  def bc_part(name, url)
    " » #{link_to_unless(current_page?(url), name, url)}"
  end

  def key_as_ascii(key)
    GPGME::Key.export key.fingerprint, armor: true
  end

  def checkbox(form, field, hint, label=nil)
    label ||= "#{field.to_s.humanize}?"
    form.input field, hint: hint, label: label, as: :boolean, wrapper: :horizontal_boolean
  end

  def generate_h1
    t = "Schleuder"
    if @title.present?
      t << " ★ #{@title}"
    end
    if @list.present?
      t << " ★ #{@list.email}"
    end
    t
  end

  def key_trust_title(key)
    t('keys.show.key_is_', status: t("keys.statuses.#{key.trust_issues}"))
  end

  def popup(icon, &block)
    render('popup', icon: icon, text: capture { block.call })
  end

  def class_for_icon(name)
    "icon_#{File.basename(name, ".*")}"
  end
end

app/views/application/_breadcrumb.html.haml
- if current_user.present?
  .breadcrumb= make_breadcrumb

app/views/application/_flashes.html.haml
- flash.each do |name, msgs|
  - Array(msgs).each do |msg|
    = content_tag :div, :class => "alert alert-#{name.to_sym == :error ? "danger" : "success" } alert-dismissable" do
      %button.close{:type => "button", :data => {:dismiss => "alert"}, :aria => {:hidden => "true"} } &times;
      = msg

app/views/application/_list_menu.html.haml
- if @list.key.blank?
  .alert.alert-warning 
    %strong
      This list is not functional!
    %p Please contact the people that run this service and tell them about this problem: "No list-key present for #{@list.email}".

- if @list.admins.blank?
  .alert.alert-warning 
    %strong
      This list is not functional!
    %p 
      It needs at least one list-admin! 
      = link_to "Please subscribe one.", new_list_subscription_path(@list)

%ul#listmenu
  - if can?(:update, @list)
    %li
      = image_tag 'people.svg', width: '20px'
      = link_to_unless_current(t(".subscriptions"), list_subscriptions_path(@list), accesskey: :s)
  - else
    %li
      %span.glyphicon.glyphicon-th-list
      = link_to_unless_current(t(".edit_subscription"), subscription_path(@subscription), accesskey: :s)
  %li
    = image_tag 'keyring.svg', width: '20px'
    = link_to_unless_current(t(".keys"), list_keys_path(@list), accesskey: :k)
  - if can?(:update, @list)
    %li
      %span.glyphicon.glyphicon-wrench
      = link_to_unless_current(t(".list_options"), edit_list_path(@list), accesskey: :o)

app/views/application/_navbar.html.haml
- if current_user.present?
  %ul.nav.navbar-nav.navbar-right
    %li#current_user_email
      = link_to(edit_account_path(current_user), title: "The account you're logged in with") do
        = current_user.email
    %li
      = link_to(root_path, accesskey: :h) do
        %span.glyphicon.glyphicon-home
        = t(".my_lists")
    %li
      = link_to(edit_account_path(current_user)) do
        %span.glyphicon.glyphicon-wrench
        = t(".account_settings")
    %li
      = link_to(destroy_login_path) do
        %span.glyphicon.glyphicon-log-out
        = t(".logout")

app/views/application/_page_header.html.haml
.page-header
  - if @list.present? && @list.persisted?
    #pageheadline= link_to @list.email, list_subscriptions_path(@list)
    = render 'list_menu'
  - else
    #pageheadline= @title

app/views/application/_popup.html.haml
.popup
  = image_tag icon, class: [:popup_icon, class_for_icon(icon)]
  .popup_text
    = text