config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get  'login/new',             to: 'logins#new', as: :new_login
  get  'login/cookiesrequired', to: 'logins#cookiesrequired', as: :cookiesrequired_login
  post 'login/create',          to: 'logins#create', as: :create_login
  get  'login/create',          to: redirect('/login/new')
  get  'login/destroy',         to: 'logins#destroy', as: :destroy_login

  post 'accounts/verify',       to: 'accounts#verify', as: :verify_account
  get  'accounts/setup/:token', to: 'accounts#setup',  as: :setup_account
  get  'accounts/:id/delete', to: 'accounts#delete',  as: :delete_account
  resources :accounts

  get 'lists/:email', to: 'lists#by_email', constraints: { email: /([\S]+@[\S]+)/ }
  get 'lists/:id/subscriptions', to: 'lists#subscriptions', as: :list_subscriptions
  get 'lists/:id/new_subscription', to: 'lists#new_subscription', as: :new_list_subscription
  get 'lists/:id/delete', to: 'lists#delete',  as: :delete_list
  resources :lists do
    get    'keys',              to: 'keys#index'
    get    'keys/new',          to: 'keys#new', as: :key_new
    get    'keys/:fingerprint', to: 'keys#show', as: :key
    delete 'keys/:fingerprint', to: 'keys#destroy'
    post   'keys',              to: 'keys#create', as: 'key_create'
  end

  resources  :subscriptions do
    member do
      get 'delete'
    end
  end

  root 'accounts#home'
end

app/models/account.rb
class Account < ApplicationRecord
  has_secure_password
  validates :email, presence: true, email: true
  before_save { email.downcase! }

  def to_s
    email
  end

  def superadmin?
    Array(Conf.superadmins).include?(self.email)
  end

  def subscribed_to?(list)
    lists.include?(list)
  end

  def subscriptions
    @subscriptions ||= Subscription.where(email: self.email)
  end

  def subscription(list)
    Subscription.where(email: self.email, list_id: list.id).first
  end

  def lists
    subscriptions.map(&:list)
  end

  def admin_lists
    Subscription.where(email: self.email, admin: true).map(&:list)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_action :authenticate, only: [:new, :verify, :setup, :create]
  skip_load_resource only: [:verify, :setup, :create]
  before_action :validate_turing_answer, only: :verify

  def index
    redirect_to root_path
  end

  def home
    @account = current_account
    show
    render 'show'
  end

  def new
    if TuringQuestion.available?
      @turing_question = TuringQuestion.random
      session[:turing_question_id] = @turing_question.id
    end
    @account = Account.new(email: session[:account_email])
    session[:account_email] = nil
  end

  def verify
    @email = params[:account][:email]
    if Account.where(email: @email).present?
      return redirect_to_new(t(".address_already_registered"))
    end

    ac_req = AccountRequest.create(email: @email)
    mail = AccountMailer.send_verification_link(@email, ac_req.token)
    if ! res = mail.deliver_now
      redirect_to_new(res)
    end
  rescue Errno::ECONNREFUSED => exc
    logger.error exc.message
    redirect_to_new(t(".smtp_connection_refused", error: exc.message))
  end

  def setup
    ac_req = AccountRequest.find_by_token!(params[:token])

    if ! ac_req.still_valid?
      render plain: t(".token_too_old")
      ac_req.destroy
      return
    end

    @account = Account.new
    @account.email = ac_req.email
    @token = ac_req.token
  end

  def create
    ac_req = AccountRequest.find_by_token!(params[:token])
    if ! res = ac_req.destroy
      logger.error "Deleting AccountRequest failed: #{res.inspect} —— AccountRequest: #{ac_req.inspect}"
      redirect_to setup_account_path, alert: t("something_went_wrong")
      return
    end

    @account = Account.new(account_params)
    @account.email = ac_req.email
    if @account.save
      redirect_to new_login_path, notice: t(".success")
    else
      render 'setup'
    end
  end

  def update
    if @account.update(account_params)
      redirect_to @account, notice: t(".password_changed")
    else
      render :edit
    end
  end

  def show
    @subscribed_lists = @account.lists
    @admin_lists = if @account.superadmin?
                     List.all
                   else
                     @account.admin_lists
                   end
    @lists = @subscribed_lists | @admin_lists
  end

  def destroy
    if @account.superadmin?
      redirect_to @account, alert: t(".superadmin_not_deletable")
      return
    end

    if account = @account.destroy
      log_out t(".success")
    else
      logger.error "Deleting account failed: #{account.inspect}"
      redirect_to account, alert: t(".failure")
    end
  end

  private

  def validate_turing_answer
    turing_question = TuringQuestion.find(session[:turing_question_id])
    session[:turing_question_id] = nil
    if turing_question.blank?
      return redirect_to_new(t("something_went_wrong"))
    end

    if turing_question.valid_answer?(params[:turing_answer])
      true
    else
      redirect_to_new(t(".invalid_answer"))
    end
  end

  def redirect_to_new(error_message)
    flash[:error] = error_message
    session[:account_email] = params[:account][:email]
    redirect_to new_account_path
    false
  end

  def render_404
    if params[:token].present?
      render 'error_404', :status => :not_found
    else
      super
    end
  end

  def account_params
    params.require(:account).permit(:password, :password_confirmation)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/delete.html.haml
- @title = "Delete account"

.col.col-sm-6
  %h2 Delete account #{@account}?

  %p{style: 'margin: 3em 0'}
    %strong 
      Are you really sure? This does 
      %em NOT
      unsubscribe you from any list!

  .pull-right
    = button_to(@account, method: :get, class: 'btn btn-link') do
      = t(".back_to_account")


  = button_to @account, method: :delete, class: 'btn btn-danger' do
    .glyphicon.glyphicon-remove
    Delete account now!

app/views/accounts/edit.html.haml
- @title = t(".title")

.col.col-sm-12
  %fieldset
    %legend
      = t(".change_password")
    = simple_form_for(@account, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
      = f.input :password, as: :password, required: true
      = f.input :password_confirmation, as: :password, required: true

      = f.submit t(".save"), class: 'btn btn-primary'

  - if ! @account.superadmin?
    .pull-right
      = link_to delete_account_path(@account), class: 'text-danger' do
        .glyphicon.glyphicon-remove
        Delete account

app/views/accounts/error_404.html.haml
%h1= t(".headline")

= simple_format(t(".explanation", link: link_to(t(".link_text"), new_account_url)).html_safe)

app/views/accounts/new.html.haml
- @title = t(".headline")

.col-lg-6.col-md-8
  = simple_form_for(@account, url: verify_account_path, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
    = f.input :email, hint: t(".email_hint")
    - if @turing_question.present?
      #turing-question.form-group
        %label.control-label.col-sm-3{for: :turing_answer}= @turing_question.question
        .col-sm-9
          = text_field_tag :turing_answer, '', class: 'form-control'
          %p.help-block= t(".turing_question_hint")

    = f.submit t(".button"), class: 'btn btn-primary'

app/views/accounts/setup.html.haml
.page-header
  %h1 Create account for #{@account}

.col-lg-5
  To complete the sign-up please choose a password for #{@account}.

  = simple_form_for(@account, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
    .form-group
      = text_field_tag 'token', @token, hidden: true
      = f.input :password
      = f.input :password_confirmation

    = f.submit 'Create Account', class: 'btn btn-primary'

  %em Note: this account and its passsword are only known to this web-interface, not to any mailing-list.

app/views/accounts/show.html.haml
- @title = t(".title")

.col.col-sm-6
  - if can? :create, List
    .pull-right
      = link_to(new_list_path, class: 'text-success') do
        %span.glyphicon.glyphicon-plus
        = t(".new_list")

  - if @lists.present?
    %h2
      = t(".headline")
    %ul
      -@lists.each do |list|
        - if @admin_lists.include?(list)
          %li
            %em= link_to list, list_subscriptions_path(list)
        -else
          %li= link_to list, subscription_path(current_account.subscription(list))

    - if @admin_lists.any?
      .text-muted
        = t(".hint")
        %em
          = t(".em")

app/views/accounts/verify.html.haml
.page-header
  %h1 Verification request sent to #{@email}

Please check your mailbox and click the link you received from &lt;#{Conf.mailer_from}&gt;.